CREATE TABLE `prime-hour-500203-q4.olist_cleaned.category_labels` AS
SELECT * FROM UNNEST([
  STRUCT('agro_industry_and_commerce' AS category_key, 'Agro & Commerce' AS category_label),
  STRUCT('air_conditioning', 'Air Conditioning'),
  STRUCT('art', 'Art'),
  STRUCT('arts_and_craftmanship', 'Arts & Crafts'),
  STRUCT('audio', 'Audio'),
  STRUCT('auto', 'Auto'),
  STRUCT('baby', 'Baby'),
  STRUCT('bed_bath_table', 'Bed, Bath & Table'),
  STRUCT('books_general_interest', 'Books - General'),
  STRUCT('books_imported', 'Books - Imported'),
  STRUCT('books_technical', 'Books - Technical'),
  STRUCT('cds_dvds_musicals', 'CDs & DVDs'),
  STRUCT('christmas_supplies', 'Christmas Supplies'),
  STRUCT('cine_photo', 'Cinema & Photo'),
  STRUCT('computers', 'Computers'),
  STRUCT('computers_accessories', 'Computer Accessories'),
  STRUCT('consoles_games', 'Consoles & Games'),
  STRUCT('construction_tools_construction', 'Construction Tools'),
  STRUCT('construction_tools_lights', 'Construction Lights'),
  STRUCT('construction_tools_safety', 'Construction Safety'),
  STRUCT('cool_stuff', 'Cool Stuff'),
  STRUCT('costruction_tools_garden', 'Garden Tools'),
  STRUCT('costruction_tools_tools', 'Tools'),
  STRUCT('diapers_and_hygiene', 'Diapers & Hygiene'),
  STRUCT('drinks', 'Drinks'),
  STRUCT('dvds_blu_ray', 'DVDs & Blu-Ray'),
  STRUCT('electronics', 'Electronics'),
  STRUCT('fashio_female_clothing', 'Female Clothing'),
  STRUCT('fashion_bags_accessories', 'Bags & Accessories'),
  STRUCT('fashion_childrens_clothes', 'Children Clothing'),
  STRUCT('fashion_male_clothing', 'Male Clothing'),
  STRUCT('fashion_shoes', 'Shoes'),
  STRUCT('fashion_sport', 'Sport Fashion'),
  STRUCT('fashion_underwear_beach', 'Underwear & Beach'),
  STRUCT('fixed_telephony', 'Fixed Telephony'),
  STRUCT('flowers', 'Flowers'),
  STRUCT('food', 'Food'),
  STRUCT('food_drink', 'Food & Drink'),
  STRUCT('furniture_bedroom', 'Bedroom Furniture'),
  STRUCT('furniture_decor', 'Furniture & Decor'),
  STRUCT('furniture_living_room', 'Living Room Furniture'),
  STRUCT('furniture_mattress_and_upholstery', 'Mattress & Upholstery'),
  STRUCT('garden_tools', 'Garden Tools'),
  STRUCT('health_beauty', 'Health & Beauty'),
  STRUCT('home_appliances', 'Home Appliances'),
  STRUCT('home_appliances_2', 'Home Appliances 2'),
  STRUCT('home_comfort_2', 'Home Comfort'),
  STRUCT('home_confort', 'Home Comfort 2'),
  STRUCT('home_construction', 'Home Construction'),
  STRUCT('housewares', 'Housewares'),
  STRUCT('industry_commerce_and_business', 'Industry & Commerce'),
  STRUCT('kitchen_dining_laundry_garden_furniture', 'Kitchen & Dining'),
  STRUCT('la_cuisine', 'La Cuisine'),
  STRUCT('luggage_accessories', 'Luggage & Accessories'),
  STRUCT('market_place', 'Marketplace'),
  STRUCT('music', 'Music'),
  STRUCT('musical_instruments', 'Musical Instruments'),
  STRUCT('office_furniture', 'Office Furniture'),
  STRUCT('party_supplies', 'Party Supplies'),
  STRUCT('perfumery', 'Perfumery'),
  STRUCT('pet_shop', 'Pet Shop'),
  STRUCT('security_and_services', 'Security & Services'),
  STRUCT('signaling_and_security', 'Signaling & Security'),
  STRUCT('small_appliances', 'Small Appliances'),
  STRUCT('small_appliances_home_oven_and_coffee', 'Oven & Coffee'),
  STRUCT('sports_leisure', 'Sports & Leisure'),
  STRUCT('stationery', 'Stationery'),
  STRUCT('tablets_printing_image', 'Tablets & Printing'),
  STRUCT('telephony', 'Telephony'),
  STRUCT('toys', 'Toys'),
  STRUCT('watches_gifts', 'Watches & Gifts')
])